name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: read
  security-events: write

env:
  GO_VERSION: '1.25'
  BINARY_NAME: 'cloudget'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          # Windows builds
          - goos: windows
            goarch: amd64
            suffix: '.exe'
          - goos: windows
            goarch: arm64
            suffix: '.exe'
          
          # Linux builds
          - goos: linux
            goarch: amd64
            suffix: ''
          - goos: linux
            goarch: arm64
            suffix: ''
          - goos: linux
            goarch: arm
            suffix: ''
          - goos: linux
            goarch: 386
            suffix: ''
          
          # macOS builds
          - goos: darwin
            goarch: amd64
            suffix: ''
          - goos: darwin
            goarch: arm64
            suffix: ''
          
          # FreeBSD builds
          - goos: freebsd
            goarch: amd64
            suffix: ''
          - goos: freebsd
            goarch: arm64
            suffix: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        mkdir -p dist
        BINARY_NAME_WITH_OS="${{ env.BINARY_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}"
        go build -a -installsuffix cgo -ldflags="-w -s" -o "dist/${BINARY_NAME_WITH_OS}" ./cmd/downloader
        
        # Create archive with renamed binary
        cd dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          cp "${BINARY_NAME_WITH_OS}" "cloudget.exe"
          zip "${BINARY_NAME_WITH_OS%.exe}.zip" "cloudget.exe"
          rm "cloudget.exe"
        else
          cp "${BINARY_NAME_WITH_OS}" "cloudget"
          tar -czf "${BINARY_NAME_WITH_OS}.tar.gz" "cloudget"
          rm "cloudget"
        fi
        cd ..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/
        retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        find artifacts -name "*.zip" -o -name "*.tar.gz" | xargs -I {} cp {} release-assets/
        
        # Create checksums
        cd release-assets
        sha256sum * > checksums.txt
        cd ..

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [ -n "$PREV_TAG" ]; then
          echo "## Changes since $PREV_TAG" > CHANGELOG.md
          git log --pretty=format:"- %s (%h)" $PREV_TAG..HEAD >> CHANGELOG.md
        else
          echo "## Initial Release" > CHANGELOG.md
          echo "First release of Cloud Downloader CLI" >> CHANGELOG.md
        fi
        
        echo "## Download" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Binaries" >> CHANGELOG.md
        echo "Download the appropriate binary for your platform:" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "| Platform | Architecture | Download |" >> CHANGELOG.md
        echo "|----------|--------------|----------|" >> CHANGELOG.md
        echo "| Windows | x86_64 | \`cloudget-windows-amd64.zip\` |" >> CHANGELOG.md
        echo "| Windows | ARM64 | \`cloudget-windows-arm64.zip\` |" >> CHANGELOG.md
        echo "| Linux | x86_64 | \`cloudget-linux-amd64.tar.gz\` |" >> CHANGELOG.md
        echo "| Linux | ARM64 | \`cloudget-linux-arm64.tar.gz\` |" >> CHANGELOG.md
        echo "| Linux | ARM | \`cloudget-linux-arm.tar.gz\` |" >> CHANGELOG.md
        echo "| Linux | i386 | \`cloudget-linux-386.tar.gz\` |" >> CHANGELOG.md
        echo "| macOS | Intel | \`cloudget-darwin-amd64.tar.gz\` |" >> CHANGELOG.md
        echo "| macOS | Apple Silicon | \`cloudget-darwin-arm64.tar.gz\` |" >> CHANGELOG.md
        echo "| FreeBSD | x86_64 | \`cloudget-freebsd-amd64.tar.gz\` |" >> CHANGELOG.md
        echo "| FreeBSD | ARM64 | \`cloudget-freebsd-arm64.tar.gz\` |" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Docker" >> CHANGELOG.md
        echo "\`\`\`bash" >> CHANGELOG.md
         echo "docker pull ghcr.io/${{ github.repository_owner }}/cloudget:${{ github.ref_name }}" >> CHANGELOG.md
        echo "\`\`\`" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Installation" >> CHANGELOG.md
        echo "1. Download the appropriate binary for your platform" >> CHANGELOG.md
        echo "2. Extract the archive" >> CHANGELOG.md
        echo "3. Make the binary executable (Linux/macOS): \`chmod +x cloudget-*\`" >> CHANGELOG.md
        echo "4. Move to a directory in your PATH (optional)" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Usage" >> CHANGELOG.md
        echo "\`\`\`bash" >> CHANGELOG.md
        echo "./cloudget-linux-amd64 -url \"https://dropbox.com/s/abc/file.zip\"" >> CHANGELOG.md
        echo "\`\`\`" >> CHANGELOG.md

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release-assets/*"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

